// <auto-generated />
using System;
using InnoClinic.Services.Patients.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoClinic.Services.Patients.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107131317_SeedPatientsToDb")]
    partial class SeedPatientsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnoClinic.Services.Patients.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLinkedToAccount")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            DateOfBirth = new DateTime(1900, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Van",
                            IsLinkedToAccount = true,
                            LastName = "Holm",
                            MiddleName = "Dark"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            IsLinkedToAccount = true,
                            LastName = "Smith",
                            MiddleName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            DateOfBirth = new DateTime(1992, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            IsLinkedToAccount = false,
                            LastName = "Doe",
                            MiddleName = "A"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            DateOfBirth = new DateTime(1978, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            IsLinkedToAccount = true,
                            LastName = "Johnson",
                            MiddleName = "B"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            DateOfBirth = new DateTime(1982, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            IsLinkedToAccount = true,
                            LastName = "Williams",
                            MiddleName = "C"
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 6,
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlie",
                            IsLinkedToAccount = false,
                            LastName = "Brown",
                            MiddleName = "D"
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 7,
                            DateOfBirth = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            IsLinkedToAccount = true,
                            LastName = "Miller",
                            MiddleName = "E"
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 8,
                            DateOfBirth = new DateTime(1988, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eva",
                            IsLinkedToAccount = false,
                            LastName = "Davis",
                            MiddleName = "F"
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 9,
                            DateOfBirth = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Frank",
                            IsLinkedToAccount = true,
                            LastName = "Martinez",
                            MiddleName = "G"
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 10,
                            DateOfBirth = new DateTime(1980, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            IsLinkedToAccount = true,
                            LastName = "Garcia",
                            MiddleName = "H"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
